feature:
  - head-branch: ["^feature", "feature", "feat"]

bug-fix:
  - head-branch: ["^fix", "fixed"]

global-config:
  - changed-files:
      - any-glob-to-any-file:
          - tooling/*

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/*

infra:
  - changed-files:
      - any-glob-to-any-file:
          - infra/*

env:
  - changed-files:
      - any-glob-to-any-file:
          - packages/env/*
