bug:
  - 'fix:'
  - 'bug:'
  - 'error:'
feature:
  - 'feat:'
enhancement:
  - 'enhancement:'
  - 'improvement:'
documentation:
  - 'docs:'
  - 'documentation:'
chore:
  - 'chore:'
style:
  - 'style:'
refactor:
  - 'refactor:'
performance:
  - 'perf:'
test:
  - 'test:'
  - 'tests:'
build:
  - 'build:'
ci:
  - 'ci:'
revert:
  - 'revert:'

'❗️ tests changes':
  - changed-files:
      - any-glob-to-any-file:
          - tests/**
'❗️ scripts changes':
  - changed-files:
      - any-glob-to-any-file:
          - scripts/**

'❗️ tooling changes':
  - changed-files:
      - any-glob-to-any-file:
          - tooling/**
'❗️ dependency updates':
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json
          - pnpm-lock.lock
