ci:
  - changed-files:
      - '.github/**'

Documentation:
  - changed-files:
      - '**/docs/*'

tests changes:
  - '**/tests/**'
scripts changes:
  - '**/scripts/**'
tooling changes:
  - '**/tooling/**'
dependency updates:
  - '**/package.json'
  - '**/package-lock.json'
  - '**/pnpm-lock.lock'
