feat:
  - head-branch: ["^feature", "feature", "feat"]

docs:
  - head-branch: ["^documentation", "documentation", "^docs", "docs"]
  - changed-files:
      - any-glob-to-any-file:
          - "**/docs/**"

db:
  - changed-files:
      - any-glob-to-any-file:
          - packages/db/**

fix:
  - head-branch: ["^fix", "fixed"]

tooling:
  - changed-files:
      - any-glob-to-any-file:
          - tooling/*

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/*

infra:
  - changed-files:
      - any-glob-to-any-file:
          - infrastructure/*

env:
  - changed-files:
      - any-glob-to-any-file:
          - packages/env/*
blog:
  - changed-files:
      - any-glob-to-any-file:
          - apps/blog/*

www:
  - changed-files:
      - any-glob-to-any-file:
          - apps/www/*

ui:
  - changed-files:
      - any-glob-to-any-file:
          - packages/ui/*

seo:
  - changed-files:
      - any-glob-to-any-file:
          - packages/seo/*

observability:
  - changed-files:
      - any-glob-to-any-file:
          - packages/observability/*

analytics:
  - changed-files:
      - any-glob-to-any-file:
          - packages/analytics/*

build:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"

logger:
  - changed-files:
      - any-glob-to-any-file:
          - packages/logger/*

email:
  - changed-files:
      - any-glob-to-any-file:
          - packages/email/*

storage:
  - changed-files:
      - any-glob-to-any-file:
          - packages/storage/*

rate-limiter:
  - changed-files:
      - any-glob-to-any-file:
          - packages/rate-limiter/*

scheuler:
  - changed-files:
      - any-glob-to-any-file:
          - packages/scheduler/*
