bug:
  - 'fix:'
  - 'bug:'
  - 'error:'
feature:
  - 'feat:'
enhancement:
  - 'enhancement:'
  - 'improvement:'
documentation:
  - 'docs:'
  - 'documentation:'
chore:
  - 'chore:'
style:
  - 'style:'
refactor:
  - 'refactor:'
performance:
  - 'perf:'
test:
  - 'test:'
  - 'tests:'
build:
  - 'build:'
ci:
  - 'ci:'
revert:
  - 'revert:'

tests changes:
  - 'tests/**'
scripts changes:
  - 'scripts/**'
tooling changes:
  - 'tooling/**'
dependency updates:
  - 'package.json'
  - 'package-lock.json'
  - 'pnpm-lock.lock'
