name: 'PNPM install'
description: 'Run pnpm install with node_modules linker and cache enabled'
inputs:
  nodeVersion:
    description: 'Use node 20+'
    required: false
    default: v20.x
runs:
  using: composite
  steps:
    - name: Use Node ${{ inputs.nodeVersion }}
      uses: buildjet/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}
    - uses: pnpm/action-setup@v2
      with:
        version: 9

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install
