# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
early_access: false
enable_free_tier: true
language: en
code_generation:
  docstrings:
    language: en-US
tone_instructions: ""
knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
chat:
  auto_reply: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: false
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: false
  review_status: true
  collapse_walkthrough: true
  path_filters: []
  path_instructions:
    - path: "**/*"
      instructions: >-
        Review the TS code, point out issues relative to principles of clean
        code, expressiveness, and performance.
  tools:
    prismaLint:
      enabled: true
    gitleaks:
      enabled: true
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      disabled_categories:
        - TYPOS
        - TYPOGRAPHY
        - CASING
      enabled_only: false
      level: default
    # biome:
    #   enabled: true
    hadolint:
      enabled: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - WIP
    labels: []
    drafts: true
    base_branches:
      - master
