packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  next:
    14.2.3
    # using this for ths blog because of an irritiating bug
    # @see https://github.com/hashicorp/next-mdx-remote/issues/467
  eslint: 9.12.0
  prettier: 3.3.3
  tailwindcss: 3.4.14
  typescript: 5.6.3
  ts-roids: 2.0.0 # always update this btw
  "@vitest/ui": 2.1.8
  vitest: "2.1.8"
  # There's a bug with the latest version as of 01.25
  # @see https://github.com/vercel/vercel/issues/11097
  vercel: "33.2.0"
  "@playwright/test": ^1.40.1
  # used to load env TS files, like @ashgw/env since next 14 only supoorts js files
  "jiti": "^2.3.3"
  "@types/node": ^20.11.17
  "@ashgw/ts-env": 1.5.3
  zod: 3.23.8
  superjson: "2.2.1"
  react-hook-form: "7.53.0"
  limico: 2.0.4

catalogs:
  react-query5:
    "@tanstack/react-query": "5.71.10"
  ts-rest3:
    "@ts-rest/core": "3.52.1"
    "@ts-rest/open-api": "3.52.1"
    "@ts-rest/react-query": "3.52.1"
    "@ts-rest/serverless": "3.52.1"
  trpc11:
    "@trpc/client": "11.0.2"
    "@trpc/next": "11.0.2"
    "@trpc/react-query": "11.0.2"
    "@trpc/server": "11.0.2"
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  prisma6:
    "@prisma/client": "6.16.2"
    prisma: "6.16.2"
    "@prisma/adapter-pg": "6.16.2"
    "@prisma/adapter-neon": "6.4.1"

  rhf:
    "@hookform/resolvers": "3.9.0"
    "react-hook-form": "7.53.0"
