packages:
  - apps/*
  - packages/*
  - tooling/*
  - assets/packaged/*

catalog:
  "@nextui-org/react": "2.2.9"
  eslint: 9.12.0
  prettier: 3.3.3
  tailwindcss: 3.4.14
  typescript: 5.6.3
  zod: 3.23.8
  next:
    14.2.3
    # using this for ths blog because of an irritiating bug
    # @see https://github.com/hashicorp/next-mdx-remote/issues/467

  ts-roids: 1.47.0 # always update this btw
  "@vitest/ui": 2.1.8
  vitest: "2.1.8"
  # There's a bug with the latest version as of 01.25
  # @see https://github.com/vercel/vercel/issues/11097
  vercel: "33.2.0"
  "@playwright/test": ^1.40.1
  # used to load env TS files, like @ashgw/env since next 14 only supoorts js files
  "jiti": "^2.3.3"
  framer-motion: ^10.17.4
  "@types/node": ^20.11.17
  "@tanstack/react-query": "5.71.10"

catalogs:
  trpc11:
    "@trpc/client": "11.0.2"
    "@trpc/next": "11.0.2"
    "@trpc/react-query": "11.0.2"
    "@trpc/server": "11.0.2"
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
