name: 'Node & pnpm'
description: 'Node and pnpm setup'
inputs:
  node_version:
    description: 'Use node 20+'
    required: false
    default: '20'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'pnpm'
