name: "Start DB and Neon Proxy (local)"
description: "Runs Postgres and local-neon-http-proxy using docker-compose"

runs:
  using: "composite"
  steps:
    - name: Install Docker Compose + deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose curl postgresql-client

    - name: Start Postgres + Proxy via Compose
      shell: bash
      working-directory: packages/db
      run: docker-compose -f compose.yml up -d

    - name: Test connection
      shell: bash
      run: |
        echo "Testing connection through proxy..."
        PGPASSWORD=postgres psql "postgres://postgres:postgres@localhost:4444/main?sslmode=disable" -c '\l'
