name: "Setup Local Database"
description: "Sets up a local PostgreSQL database for testing"

runs:
  using: "composite"
  steps:
    - name: Set up Docker
      shell: bash
      run: |
        # Export UID/GID for Docker compose
        echo "UID=$(id -u)" >> $GITHUB_ENV
        echo "GID=$(id -g)" >> $GITHUB_ENV

    - name: Start local database
      shell: bash
      run: |
        cd packages/db
        docker compose up -d
        # Wait for database to be ready
        timeout 30s bash -c 'until docker exec ashgw_local_pg pg_isready -U postgres; do sleep 1; done'
        cd ../..

    - name: Run database migrations
      shell: bash
      run: |
        export DATABASE_URL="postgres://postgres:postgres@localhost:5432/main"
        cd packages/db
        npx prisma migrate deploy
        cd ../..

    - name: Run database seeder
      shell: bash
      run: |
        export DATABASE_URL="postgres://postgres:postgres@localhost:5432/main"
        pnpm --filter @ashgw/seeder seed
