name: "Start DB and Neon Proxy (local)"
description: "Runs Postgres and local-neon-http-proxy using docker-compose"

runs:
  using: "composite"
  steps:
    - name: Install Docker Compose + deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose curl postgresql-client

    - name: Start Postgres + Proxy via Compose
      shell: bash
      working-directory: packages/db
      run: docker-compose -f compose.yml up -d

    - name: Wait for Proxy to be ready
      shell: bash
      run: |
        echo "⏳ Waiting for Neon proxy on port 4444..."
        for i in {1..30}; do
          if curl --fail http://localhost:4444/health; then
            echo "✅ Neon proxy is up"
            break
          fi
          echo "Waiting ($i)..."
          sleep 2
        done
