name: Ephemeral Postgres
description: Start a simple temporary Postgres in Docker

runs:
  using: "composite"
  steps:
    - name: Set up Docker for the temporary database container
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
    - name: Run Postgres
      id: pg
      shell: bash
      run: |
        set -euo pipefail
        docker rm -f pg-test >/dev/null 2>&1 || true
        docker run -d --name pg-test -p 5432:5432 \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -e POSTGRES_DB=main \
          postgres:16

        echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/main" >> "$GITHUB_OUTPUT"
