name: CI / DB Migrate

description: Run database migrations on a fresh DB

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/ephermal-db
    - name: Test migrations in an ephemeral Docker container
      shell: bash
      run: |
        if [[ "$DATABASE_URL" != *"localhost"* ]] && [[ "$DATABASE_URL" != *"127.0.0.1"* ]]; then
          echo "❌ DATABASE_URL is not local! Aborting."
          exit 1
        fi

        pnpm --filter @ashgw/db start

        echo "Waiting for DB to be ready..."
        for i in {1..30}; do
          pg_isready -h localhost -p 5432 -U postgres && break
          sleep 2
        done

        echo "Running migration reset..."
        pnpm --filter @ashgw/db migrate:reset --force

        echo "Validating migrations..."
        pnpm --filter @ashgw/db migrate:status

        STATUS=$?
        echo "Cleaning up..."
        pnpm --filter @ashgw/db stop

        exit $STATUS
