name: Vercel Deployment

description: Deploy to Vercel and set the URL

inputs:
  deployment_environment:
    description: "Environment, either 'production' or 'preview' (this will determine which image is pushed and where it redeploys)"
    required: true
  APP_NAME:
    description: "The working directory/project name you're trying to deploy. Example: 'www', 'blog'"
    required: true
  VERCEL_TOKEN:
    description: "Vercel token for authentication"
    required: true
  GITHUB_TOKEN:
    description: "GitHub toaken"
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy to Vercel
      shell: bash
      run: |
        if [ "${{ inputs.deployment_environment }}" == "preview" ]; then
          cd apps/${{ inputs.APP_NAME }} && \
          PREVIEW_URL=$(pnpm --filter @ashgw/${{ inputs.APP_NAME }} deploy:vercel-preview --token=${{ inputs.VERCEL_TOKEN }} | grep -Eo 'https?://[^ ]+')
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
          echo "::notice title=Preview URL::$PREVIEW_URL"
          echo "preview-url=$PREVIEW_URL" >> $GITHUB_OUTPUT
        else
          cd apps/${{ inputs.APP_NAME }} && \
          PROD_URL=$(pnpm --filter @ashgw/${{ inputs.APP_NAME }} deploy:vercel-production --token=${{ inputs.VERCEL_TOKEN }} | grep -Eo 'https?://[^ ]+')
          echo "::notice title=Production URL::$PROD_URL"
          echo "production-url=$PROD_URL" >> $GITHUB_OUTPUT
        fi

    - name: Notify mfs about the deployment URL
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Preview Deployment Ready! 

            ### Project: \`${process.env.APP_NAME}\`
            
            **Preview URL:** [Check it out here](${process.env.PREVIEW_URL})
            
            ---
            > This preview environment reflects the changes in this PR. And deploys this version of the app as soons as the "deploy-preview" label is added`
          })
