// Generated by nitro
import type { Serialize, Simplify } from "nitropack";

declare module "nitropack" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
  interface InternalApi {
    "/r/**:auth": {
      default: Simplify<
        Serialize<
          Awaited<ReturnType<typeof import("../../routes/r/[...auth]").default>>
        >
      >;
    };
  }
}
export {};
