name: Vercel Build

description: Build to deploy to vercel

inputs:
  APP_NAME:
    description: "The working directory/project name you're trying to build. Example: 'www', 'blog'"
    required: true
  VERCEL_TOKEN:
    description: "Vercel token for authentication"
    required: true
  VERCEL_ORG_ID:
    description: "Vercel organization ID"
    required: true
  VERCEL_PROJECT_ID:
    description: "Vercel project ID"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/pnpm-install
    - name: Build for Vercel
      shell: bash
      env:
        VERCEL_TOKEN: ${{ inputs.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ inputs.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ inputs.VERCEL_PROJECT_ID }}
      run: |
        cd apps/${{ inputs.APP_NAME }} && pnpm --filter @ashgw/${{ inputs.APP_NAME }} build:vercel-${{ inputs.NODE_ENV }} --token=$VERCEL_TOKEN
