name: Vercel Build

description: Build to deploy to vercel

inputs:
  deployment_environment:
    description: "The environment to build for. Example: 'preview', 'production'"
    required: true
  app_name:
    description: "The working directory/project name you're trying to build. Example: 'www', 'blog'"
    required: true
  VERCEL_TOKEN:
    description: "Vercel token for authentication"
    required: true
  VERCEL_ORG_ID:
    description: "Vercel organization ID"
    required: true
  VERCEL_PROJECT_ID:
    description: "Vercel project ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build for Vercel (prebuilt)
      shell: bash
      env:
        VERCEL_TOKEN: ${{ inputs.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ inputs.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ inputs.VERCEL_PROJECT_ID }}
      run: |
        pnpm vercel pull --yes --environment=${{ inputs.deployment_environment }} --token=$VERCEL_TOKEN
        pnpm vercel build --yes
