name: "Setup Environment Variables"
description: "Sets up env from GitHub Secrets"
inputs:
  NODE_ENV:
    description: "either 'development', 'preview', or 'production' & defo not 'prod' or 'dev'"
    required: true
  NEXT_PUBLIC_WWW_URL:
    required: true
  NEXT_PUBLIC_BLOG_URL:
    required: true
  NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID:
    required: true
  NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID:
    required: true

runs:
  using: composite
  steps:
    - name: Set up .env
      shell: bash
      run: |
        declare -A env_vars=(
          ["NODE_ENV"]="${{ inputs.NODE_ENV }}"
          ["NEXT_PUBLIC_WWW_URL"]="${{ inputs.NEXT_PUBLIC_WWW_URL }}"
          ["NEXT_PUBLIC_BLOG_URL"]="${{ inputs.NEXT_PUBLIC_BLOG_URL }}"
          ["NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID"]="${{ inputs.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}"
          ["NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID"]="${{ inputs.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}"
        )

        for key in "${!env_vars[@]}"; do
          echo "${key}='${env_vars[$key]}'" >> .env
        done
