name: Setup Environment Variables
description: Export secrets from Doppler to the job environment

inputs:
  ENV_SERVICE_TOKEN:
    required: true
    description: "Doppler service token (scoped to the desired project/config) with the current GH environment"

runs:
  using: "composite"
  steps:
    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v3

    - name: Fetch env from Doppler
      shell: bash
      env:
        DOPPLER_TOKEN: ${{ inputs.ENV_SERVICE_TOKEN }}
        DOPPLER_UPDATE_CHECKS: "false"
        DOPPLER_TELEMETRY_DISABLED: "1"
      run: |
        set -euo pipefail

        if [[ -z "${DOPPLER_TOKEN:-}" ]]; then
          echo "ENV_SERVICE_TOKEN is required" >&2
          exit 1
        fi

        doppler secrets download --no-file --format env | while IFS= read -r line; do
          # only handle KEY=VALUE lines
          [[ "$line" != *=* ]] && continue

          key="${line%%=*}"
          val="${line#*=}"

          # strip inline comments like: VALUE # comment
          val="${val%%#*}"

          # trim leading/trailing whitespace
          val="$(printf '%s' "$val" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

          # strip surrounding quotes if present
          if [[ "$val" == \"*\" && "$val" == *\" ]]; then
            val="${val:1:${#val}-2}"
          fi
          if [[ "$val" == \'*\' && "$val" == *\' ]]; then
            val="${val:1:${#val}-2}"
          fi

          # mask value in logs
          echo "::add-mask::$val"

          # write to GITHUB_ENV (handles equals and spaces fine)
          printf '%s=%s\n' "$key" "$val" >> "$GITHUB_ENV"
        done
