name: Setup Environment Variables
description: Export secrets

inputs:
  ENV_SERVICE_TOKEN:
    required: true
    description: "Doppler service token scoped to the correct environment (prod/preview/dev)"

# will use doppler secrets
runs:
  using: composite
  steps:
    - name: Fetch env from Doppler
      shell: bash
      run: |
        set -euo pipefail

        export DOPPLER_TOKEN="${{ inputs.ENV_SERVICE_TOKEN }}"

        doppler secrets download --no-file --format env | while IFS= read -r line; do
          # Mask each value in logs
          if [[ "$line" == *=* ]]; then
            key="${line%%=*}"
            val="${line#*=}"
            echo "::add-mask::$val"
            echo "$line" >> "$GITHUB_ENV"
          fi
        done
