name: Ephermal DB
description: Create an ephermal local Postgres DB

runs:
  using: "composite"
  steps:
    - name: Set up Docker for the temporary database container
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
    - name: Mask database url
      shell: bash
      run: |
        set -euo pipefail
        if [[ -z "${DATABASE_URL:-}" ]]; then
          echo "DATABASE_URL is not set"; exit 1
        fi
        echo "::add-mask::$DATABASE_URL"

    - name: Setup ephemeral DB
      shell: bash
      run: |
        pnpm --filter @ashgw/db start

        echo "Waiting for DB to be ready..."
        for i in {1..30}; do
          pg_isready -h localhost -p 5432 -U postgres && break
          sleep 2
        done
        echo 'Database is now ready to accept connections!'
        # I already injected the $DATABASE_URL, it's localhost

    - name: Seed the database
      shell: bash
      run: |
        pnpm --filter @ashgw/seeder seed

