version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ashgw_local_pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 2s
      retries: 10

  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    container_name: ashgw_neon_proxy
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@db:5432/main
    ports:
      - "4444:4444"

volumes:
  pg_data:
