name: Container Deployment

description: Build and deploy container image

inputs:
  deployment_environment:
    description: "Environment, either 'production' or 'preview' (this will determine which image is pushed and where it redeploys)"
    required: true
    default: "preview"
  app_name:
    description: "App name, either 'blog' or 'www' or whatever app you're running"
    required: true
  NOTIFY_TOKEN:
    description: "Notify token"
    required: true
  CONTAINER_DEPLOYMENT_SERVICE_TOKEN:
    description: "API token"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token with packages:write for GHCR and PR comments"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to GHCR
      shell: bash
      run: |
        echo "${{ inputs.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build image with script
      id: build
      shell: bash
      run: |
        set -euo pipefail
        START_TS=$(date +%s)
        echo "start_ts=$START_TS" >> "$GITHUB_OUTPUT"

        IMAGE="ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:${{ inputs.deployment_environment }}"
        ./deployment/${{ inputs.app_name }}/build \
          --env "${{ inputs.deployment_environment }}" \
          --service "${{ inputs.app_name }}" \
          --image "$IMAGE"

    - name: Push image (production + latest)
      if: ${{ inputs.deployment_environment == 'production' }}
      shell: bash
      run: |
        IMAGE="ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:production"
        LATEST="ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:latest"
        docker push "$IMAGE"
        docker tag "$IMAGE" "$LATEST"
        docker push "$LATEST"

    - name: Push image (preview)
      if: ${{ inputs.deployment_environment == 'preview' }}
      shell: bash
      run: |
        IMAGE="ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:preview"
        docker push "$IMAGE"

    - name: Install Koyeb CLI and redeploy
      shell: bash
      run: |
        # Write Koyeb CLI config
        cat > "$HOME/.koyeb.yaml" << EOF
        debug: false
        organization: ""
        token: ${{ inputs.CONTAINER_DEPLOYMENT_SERVICE_TOKEN }}
        url: https://app.koyeb.com
        EOF

        # Install CLI
        curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
        export PATH="$HOME/.koyeb/bin:$PATH"

        # Choose target
        if [[ "${{ inputs.deployment_environment }}" == "production" ]]; then
          echo "Deploying to production environment"
          DEPLOY_TARGET="${{ inputs.app_name }}/${{ inputs.app_name }}"
        elif [[ "${{ inputs.deployment_environment }}" == "preview" ]]; then
          echo "Deploying to preview environment"
          DEPLOY_TARGET="${{ inputs.app_name }}-preview/${{ inputs.app_name }}-preview"
        else
          echo "Unknown environment: ${{ inputs.deployment_environment }}"
          exit 1
        fi

        # Redeploy
        koyeb service redeploy "$DEPLOY_TARGET"

    - name: Capture end timestamp
      id: end
      shell: bash
      run: |
        END_TS=$(date +%s)
        echo "end_ts=$END_TS" >> "$GITHUB_OUTPUT"

    - name: Compute duration
      id: duration
      shell: bash
      run: |
        echo "seconds=$(( ${{ steps.end.outputs.end_ts }} - ${{ steps.build.outputs.start_ts }} ))" >> "$GITHUB_OUTPUT"

    - name: Notify about preview deployment
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
      env:
        DEPLOYED_APP: ${{ inputs.app_name }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          const app = process.env.DEPLOYED_APP;
          const body = [
            `## ${app} Preview Deployment Ready`,
            ``,
            `**App:** \`${app}\``,
            ``,
            `**Preview URL:** [${app}-preview.ashgw.me](https://${app}-preview.ashgw.me)`,
            ``,
            `---`,
            `This preview reflects the changes in this PR. It auto-deploys when the \`deploy-preview\` label is applied.`
          ].join("\n");
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          });

    - name: Notify • Deploy OK
      if: success()
      uses: ashgw/notify@main
      with:
        token: ${{ inputs.NOTIFY_TOKEN }}
        title: "Deployment Succeeded"
        message: |
          ### Details
          - **App:** ${{ inputs.app_name }}
          - **Environment:** `${{ inputs.deployment_environment }}`
          - **Actor:** @${{ github.actor }}
          - **Commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          - **Run:** [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - **Duration:** ${{ steps.duration.outputs.seconds }} seconds

          ---
          The application is now live.

    - name: Notify • Deploy Fail
      if: failure()
      uses: ashgw/notify@main
      with:
        token: ${{ inputs.NOTIFY_TOKEN }}
        title: "Deployment Failed"
        message: |
          ### Details

          - **App:** ${{ inputs.app_name }}
          - **Environment:** ${{ inputs.deployment_environment }}
          - **Actor:** @${{ github.actor }}
          - **Commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          - **Run:** [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - **Duration:** ${{ steps.duration.outputs.seconds }} seconds

          ---
          Redeploy attempt failed. Check workflow logs for details.
