name: Koyeb Preview Deployment

description: Build and deploy container image to Koyeb via GHCR

inputs:
  NODE_ENV:
    description: "Node environment, either 'production' or 'preview' (this will determine which image is pushed & redeployed & where)"
    required: true
    default: "preview"
  KOYEB_TOKEN:
    description: "Koyeb API token"
    required: true
  SERVICE_NAME:
    description: "Koyeb service name, either 'blog' or 'www' or whatever app, you're running"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token with packages:write for GHCR and PR comments"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to GHCR
      shell: bash
      run: |
        echo "${{ inputs.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build Docker Image
      shell: bash
      run: |
        IMAGE="ghcr.io/${{ github.repository_owner }}/${{ inputs.SERVICE_NAME }}:${{ inputs.NODE_ENV }}"
        docker build -t "$IMAGE" -f deployment/${{ inputs.SERVICE_NAME }}/Dockerfile .

    - name: Push Production Image (also tag latest)
      if: ${{ inputs.NODE_ENV == 'production' }}
      shell: bash
      run: |
        IMAGE="ghcr.io/${{ github.repository_owner }}/${{ inputs.SERVICE_NAME }}:${{ inputs.NODE_ENV }}"
        LATEST="ghcr.io/${{ github.repository_owner }}/${{ inputs.SERVICE_NAME }}:latest"
        docker push "$IMAGE"
        docker tag "$IMAGE" "$LATEST"
        docker push "$LATEST"

    - name: Push Preview Image
      if: ${{ inputs.NODE_ENV == 'preview' }}
      shell: bash
      run: |
        IMAGE="ghcr.io/${{ github.repository_owner }}/${{ inputs.SERVICE_NAME }}:preview"
        docker push "$IMAGE"

    - name: Install Koyeb CLI and Redeploy
      shell: bash
      run: |
        # Create the Koyeb config file directly
        cat > $HOME/.koyeb.yaml << EOF
        debug: false
        organization: ""
        token: ${{ inputs.KOYEB_TOKEN }}
        url: https://app.koyeb.com
        EOF

        # Install and configure CLI
        curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
        export PATH=$HOME/.koyeb/bin:$PATH

        IMAGE_BASE="ghcr.io/${{ github.repository_owner }}/${{ inputs.SERVICE_NAME }}"
        if [[ "${{ inputs.NODE_ENV }}" == "production" ]]; then
          IMAGE_TAG="latest"
        else
          IMAGE_TAG="preview"
        fi
        IMAGE="${IMAGE_BASE}:${IMAGE_TAG}"

        # Determine target based on NODE_ENV
        if [[ "${{ inputs.NODE_ENV }}" == "production" ]]; then
          echo "Deploying to production environment"
          DEPLOY_TARGET="${{ inputs.SERVICE_NAME }}/${{ inputs.SERVICE_NAME }}"
        elif [[ "${{ inputs.NODE_ENV }}" == "preview" ]]; then
          echo "Deploying to preview environment"
          DEPLOY_TARGET="${{ inputs.SERVICE_NAME }}-preview/${{ inputs.SERVICE_NAME }}-preview"
        else
          echo "Unknown NODE_ENV: ${{ inputs.NODE_ENV }}"
          exit 1
        fi

        koyeb service redeploy "$DEPLOY_TARGET"

    - name: Notify about preview deployment
      if: ${{ inputs.NODE_ENV == 'preview' }}
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## ${process.env.SERVICE_NAME} Preview Deployment Ready! 

            ### Service: \`${process.env.SERVICE_NAME}\`
            
            **Preview URL:** [Check it out here](https://${process.env.SERVICE_NAME}-preview.ashgw.me)
            
            ---
            > This preview environment reflects the changes in this PR. And deploys this version of the app as soons as the "deploy-preview" label is added`
          })
