name: Blog Preview on Label

on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  trigger-workflow:
    if: github.event.label.name == 'ready-for-preview'
    uses: ./.github/workflows/blog-preview-deployment.yml
    secrets: inherit
