name: CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          ENV_VARS: ${{ secrets.ENV_VARS }}
          GA_ID: ${{ secrets.GA_ID }}
