name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr:
    uses: ./.github/workflows/validate-pr-title.yml
    secrets: inherit

  format:
    uses: ./.github/workflows/format.yml
    secrets: inherit

  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  secrets-leaks:
    uses: ./.github/workflows/secrets-leaks.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  mergeable:
    if: always()
    needs:
      - format
      - lint
      - test
      - secrets-leaks
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}

  www-preview-deployemnt:
    needs: [mergeable]
    uses: ./.github/workflows/www-preview-deployment.yml
    secrets: inherit

  blog-preview-deployemnt:
    needs: [mergeable]
    uses: ./.github/workflows/blog-preview-deployment.yml
    secrets: inherit

  # This is merely a trigger, so I can manually dispatch all prod deployments
  production-deployemnt:
    needs: [mergeable]
    uses: ./.github/workflows/production-deployment.yml
    secrets: inherit

  www-production-deployemnt:
    needs: [production-deployemnt]
    uses: ./.github/workflows/www-production-deployment.yml
    secrets: inherit

  blog-production-deployemnt:
    needs: [production-deployemnt]
    uses: ./.github/workflows/blog-production-deployment.yml
    secrets: inherit

  # add this back when you deploy the api
  # container-registry:
  #   needs: [production-deployemnt]
  #   uses: ./.github/workflows/container-registry.yml
  #   secrets: inherit
