name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr:
    # conventional commit validation
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/on-workflow-call-pr-validate-title.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write

  summarize-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/on-workflow-call-pr-summarize.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write

  format:
    uses: ./.github/workflows/on-workflow-call-format.yml
    secrets: inherit
    permissions:
      contents: read

  dependencies-check:
    uses: ./.github/workflows/on-workflow-call-dependencies-check.yml
    secrets: inherit
    permissions:
      contents: read

  lint:
    uses: ./.github/workflows/on-workflow-call-lint.yml
    secrets: inherit
    permissions:
      contents: read

  secrets-leaks:
    uses: ./.github/workflows/on-workflow-call-secrets-leaks.yml
    secrets: inherit
    permissions:
      contents: read

  build:
    uses: ./.github/workflows/on-workflow-call-build.yml
    secrets: inherit
    permissions:
      contents: read

  test:
    uses: ./.github/workflows/on-workflow-call-test.yml
    secrets: inherit
    permissions:
      contents: read

  db-migration:
    uses: ./.github/workflows/on-workflow-call-db-migrate.yml
    secrets: inherit
    with:
      environment: development
      # if we just merged, run the migration deployment step on the current dev branch
      # we can also migrate deploy from a label added to the PR
      # this makes sure we deploy the migration anyway on merge
      with_deploy: ${{ github.ref == 'refs/heads/main' && 'yes' || 'no' }}
    permissions:
      contents: read

  mergeable:
    if: always()
    needs:
      - format
      - lint
      - test
      - secrets-leaks
      - build
      - dependencies-check
      - db-migration
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}
    permissions:
      contents: read

  # just a trigger to dispatch
  preview-deployment:
    needs: [mergeable]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/on-workflow-call-preview-deployment.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write

  www-prevew-deployemnt:
    needs: [preview-deployment]
    uses: ./.github/workflows/on-workflow-call-www-preview-deployment.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write

  blog-preview-deployemnt:
    needs: [preview-deployment]
    uses: ./.github/workflows/on-workflow-call-blog-preview-deployment.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write

  # same here
  production-deployment:
    if: github.ref == 'refs/heads/main'
    needs: [mergeable]
    uses: ./.github/workflows/on-workflow-call-production-deployment.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write

  www-production-deployment:
    needs: [production-deployment]
    uses: ./.github/workflows/on-workflow-call-www-production-deployment.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write

  blog-production-deployment:
    needs: [production-deployment]
    uses: ./.github/workflows/on-workflow-call-blog-production-deployment.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
