name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: Release
  cancel-in-progress: false

jobs:
  validate-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/validate-pr.yml
    secrets: inherit

  format:
    uses: ./.github/workflows/format.yml
    secrets: inherit

  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  secrets-leaks:
    uses: ./.github/workflows/secrets-leaks.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  mergeable:
    if: always()
    needs:
      - format
      - lint
      - test
      - secrets-leaks
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}

  container-registry:
    if: github.ref == 'refs/heads/main'
    needs:
      - mergeable
    uses: ./.github/workflows/container-registry.yml
    secrets: inherit

  deploy-prod:
    if: github.ref == 'refs/heads/main' && github.triggering_actor == 'ashgw'
    needs: [mergeable]
    uses: ./.github/workflows/production-deployment.yml
    secrets: inherit
