name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:
    inputs:
      app:
        description: "App to deploy (manual runs only)"
        required: true
        type: choice
        options:
          - both
          - www
          - blog
        default: both
      environment:
        description: "Target environment (manual runs only)"
        required: true
        type: choice
        options:
          - preview
          - production
        default: preview

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/on-workflow-call-pr-validate-title.yml
    secrets: inherit

  validate-env:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/on-workflow-call-validate-env.yml
    secrets: inherit

  summarize-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/on-workflow-call-pr-summarize.yml
    secrets: inherit

  format:
    uses: ./.github/workflows/on-workflow-call-format.yml
    secrets: inherit

  dependencies-check:
    uses: ./.github/workflows/on-workflow-call-dependencies-check.yml
    secrets: inherit

  lint:
    uses: ./.github/workflows/on-workflow-call-lint.yml
    secrets: inherit

  secrets-leaks:
    uses: ./.github/workflows/on-workflow-call-secrets-leaks.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/on-workflow-call-build.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/on-workflow-call-test.yml
    secrets: inherit

  db-fresh-migration:
    uses: ./.github/workflows/on-workflow-call-ephermal-db-migrate.yml
    secrets: inherit

  mergeable:
    if: always()
    needs:
      - validate-env
      - format
      - lint
      - test
      - secrets-leaks
      - build
      - dependencies-check
      - db-fresh-migration
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}

  # trigger preview gate
  preview-deployment:
    needs: [mergeable]
    if: (github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'preview')
    uses: ./.github/workflows/on-workflow-call-trigger-deployment.yml
    with:
      deployment_environment: preview
    secrets: inherit

  www-preview-deployment:
    needs: [preview-deployment]
    if: needs.preview-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'www' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-serverless-deployment.yml
    with:
      deployment_environment: preview
      app_name: www
    secrets: inherit

  blog-preview-deployment:
    needs: [preview-deployment]
    if: needs.preview-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'blog' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-container-deployment.yml
    with:
      deployment_environment: preview
      app_name: blog
    secrets: inherit

  production-deployment:
    needs: [mergeable]
    if: (github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'production')
    uses: ./.github/workflows/on-workflow-call-trigger-deployment.yml
    with:
      deployment_environment: production
    secrets: inherit

  www-production-deployment:
    needs: [production-deployment]
    if: needs.production-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'www' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-serverless-deployment.yml
    with:
      deployment_environment: production
      app_name: www
    secrets: inherit

  blog-production-deployment:
    needs: [production-deployment]
    if: needs.production-deployment.result == 'success' && (github.event_name != 'workflow_dispatch' || inputs.app == 'blog' || inputs.app == 'both')
    uses: ./.github/workflows/on-workflow-call-container-deployment.yml
    with:
      deployment_environment: production
      app_name: blog
    secrets: inherit
