name: Cron / Purge Trashed Posts

on:
  schedule:
    # run on the 1st of every month at 02:20 UTC
    - cron: "20 2 1 * *"
  workflow_dispatch:

jobs:
  purge_trash_posts:
    runs-on: ubuntu-latest

    # environment: production don't ask me & run auto
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SUBMODULE_SYNC_PAT }}

      - name: Purge Trash Posts
        shell: bash
        run: .github/scripts/cron/purge-trash-posts.sh

      - name: Notify • cron ok
        if: success()
        uses: ashgw/notify@main
        with:
          token: ${{ secrets.PRODUCTION_NOTIFICATION_TOKEN }}

          title: "Cron Succeeded"
          message: >-
            ## Details

            - Monthly trash purge succeeded on ${{ env.NEXT_PUBLIC_WWW_URL }}.

            - **Run:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Notify • cron fail
        if: failure()
        uses: ashgw/notify@main
        with:
          token: ${{ secrets.PRODUCTION_NOTIFICATION_TOKEN }}

          title: "Cron Failed"
          message: >-
            ## Details

            - Monthly trash purge failed on ${{ env.NEXT_PUBLIC_WWW_URL }}.

            - **Run:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
