name: push

on:
  push:
    branches: main

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up .env
        run: echo '${{ secrets.ENV_VARS }}' >> .env.all
      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p \"require('./package.json').version\")"
      - name: Building & tagging
        run: |
          docker build -t ashgw/mysite:${{ steps.get_version.outputs.version }} .
          docker tag ashgw/mysite:${{ steps.get_version.outputs.version }} ashgw/mysite:latest
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ashgw --password-stdin
      - name: Pushing
        run: |
          docker push ashgw/mysite:${{ steps.get_version.outputs.version }}
          docker push ashgw/mysite:latest
