name: CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/setup-env
        with:
          ENV_VARS: ${{ secrets.ENV_VARS }}
          GA_ID: ${{ secrets.GA_ID }}
      - name: format
        run: pnpm format
