name: Dispatch / update-changelog

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write
  repository-projects: write

jobs:
  update-changelog:
    if: github.event.label.name == 'update-changelog' && github.actor == 'ashgw'
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GA_AUTOMATIONS_PR_RW }}" > ~/.gh_token
          gh auth login --hostname github.com --with-token < ~/.gh_token
          gh auth status

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: ./.github/actions/pnpm-install

      - name: Run Changeset versioning
        run: pnpm changelog:version

      - name: Create changelog PR
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          RANDOM_SUFFIX: ${{ github.run_id }}
        run: |
          BRANCH_NAME="changelog-update-${PR_NUMBER}-${RANDOM_SUFFIX}"
          git checkout -b "${BRANCH_NAME}"

          git config user.name "ashgw-bot"
          git config user.email "ashgw@users.noreply.github.com"

          git add .
          git commit -m "chore: changelog + version bump" || echo "Nothing to commit"
          git push origin "${BRANCH_NAME}"

          gh pr create \
            --title "chore: changelog update for PR #${PR_NUMBER}" \
            --body "This PR contains changelog updates and version bumps for PR #${PR_NUMBER}" \
            --base "${GITHUB_HEAD_REF}" \
            --head "${BRANCH_NAME}"
