name: Dispatch

on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  blog-deploy-preview:
    if: github.event.label.name == 'deploy-preview'
    uses: ./.github/workflows/on-workflow-call-blog-preview-deployment.yml
    secrets: inherit
