name: Dispatch

on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  migrate-deploy-development:
    if: github.event.label.name == 'migrate-deploy'
    uses: ./.github/workflows/on-workflow-call-db-migrate.yml
    with:
      with_deploy: "yes"
    secrets: inherit
