# this auto labels PRs based on the configuration file
# have a look at ./github/labeler.yml`
name: PR

on:
  - pull_request_target

jobs:
  label-triage:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ashgw' && github.event.pull_request.head.repo.fork == false
    permissions:
      contents: read
      pull-requests: write
    steps:
      # Check out base repository main to avoid executing untrusted PR refs
      - uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
