name: Dispatch

on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  www-deploy-preview:
    if: github.event.label.name == 'deploy-preview'
    uses: ./.github/workflows/on-workflow-call-www-deployment.yml
    with:
      deployment_environment: preview
      add_comment: true
    secrets: inherit
