name: Dispatch

on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  www-deploy-preview:
    if: github.event.label.name == 'deploy-preview'
    uses: ./.github/workflows/on-workflow-call-serverless-deployment.yml
    with:
      deployment_environment: preview
      app_name: www
    secrets: inherit
