# this auto labels PRs based on the configuration file
# have a look at ./github/labeler.yml`
name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  label-triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ashgw' && github.event.pull_request.head.repo.fork == false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
