name: CI / update changest

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write # this is needed to allow pushing tags and committing

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/pnpm-install
      - name: Run Changeset version
        run: pnpm changeset version

      - name: Commit and push changelog + bumps
        run: |
          # git config user.email "actions@github.com" # looks ugly as hell dawg frfr
          # git config user.name "github-actions"
          git add .
          git commit -m "chore: version bump via changesets [skip ci]" || echo "No changes to commit"
          git push origin main --follow-tags
