name: CI / Database Migration

on:
  workflow_call:
    inputs:
      with_deploy:
        required: true
        type: string
        description: "Whether to run the deploy step ('yes' or 'no')"

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_SUBMODULE_SYNC_PAT }}

      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/setup-env
        with:
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}

      - uses: ./.github/actions/db-migrate
        with:
          with_deploy: ${{ inputs.with_deploy }}
