name: CD / Docker App Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string
        description: blog or www or whatever, basically the app

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}

      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/db-migrate
        with:
          with_deploy: "yes"
          environment: ${{ inputs.environment }}

      - uses: ./.github/actions/container-deploy
        with:
          environment: ${{ inputs.environment }}
          CONTAINER_DEPLOYMENT_SERVICE_TOKEN: ${{ secrets.CONTAINER_DEPLOYMENT_SERVICE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT_BLOG }}
          APP_NAME: ${{ inputs.APP_NAME}} # only blog for now

