name: CD / Blog production deployment

on:
  workflow_call:
    inputs:
      deployment_environment:
        required: true
        type: string
        description: "Environment to deploy to (preview or production)"
      add_comment:
        description: "Add a comment notification to the PR"
        required: false
        type: string
        default: "false"

permissions:
  pull-requests: write # needed for adding comments
  contents: read # needed for reading secrets
  issues: write # needed for adding comments

jobs:
  deploy:
    uses: ./.github/workflows/on-workflow-call-container-deployment.yml
    with:
      environment: ${{ inputs.deployment_environment }}
      SERVICE_NAME: "blog"
    secrets: inherit
