name: Preview Deployment

on:
  workflow_call:

jobs:
  deploy-preview:
    environment: preview
    name: Trigger Preview Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 1
    concurrency:
      group: preview-deploy
      cancel-in-progress: false
    steps:
      - name: Send Notification
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.actor
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'preview_deploy_started',
              client_payload: {
                message: `🚀 Preview deployment started by @${creator}`,
                triggered_at: new Date().toISOString()
              }
            })
      - name: Success
        run: |
          echo "::notice title=Preview Deploy::Deployment started by @${{ github.actor }} at $(date)"
          echo "Deployment triggered successfully"
