name: CD / Blog preview deployment

on:
  workflow_call:

permissions:
  pull-requests: write # needed for adding comments
  contents: read # needed for reading secrets
  issues: write # needed for adding comments

jobs:
  deploy:
    uses: ./.github/workflows/on-workflow-call-container-deployment.yml
    with:
      NODE_ENV: "preview"
      SERVICE_NAME: "blog"
    secrets: inherit
