name: CD / WWW preview deployment

on:
  workflow_call:
    inputs:
      add_comment:
        description: "Add a comment notification to the PR"
        required: false
        type: string
        default: "false"

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  deploy:
    environment: preview
    env:
      DEPLOY_ENV: preview

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/vercel-build
        with:
          project_name: www
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}
          # deplyment specific, not needed for build
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WWW_PROJECT_ID }}
      - uses: ./.github/actions/db-migrate
        with:
          with_deploy: "yes"
          environment: ${{ env.DEPLOY_ENV }}

      - uses: ./.github/actions/vercel-deploy
        with:
          project_name: www
          environment: ${{ env.DEPLOY_ENV }}
          add_comment: ${{ inputs.add_comment }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
