name: CD / Docker App Deployment

on:
  workflow_call:
    inputs:
      NODE_ENV:
        required: true
        type: string
      SERVICE_NAME:
        required: true
        type: string
        description: blog or www or whatever, basically the app

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ inputs.SERVICE_NAME }}-${{ inputs.NODE_ENV }}
      cancel-in-progress: false
    # environment: ${{ inputs.NODE_ENV }} # this is needed since some secrets are valid (not fake) only in this env type & higher
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          NODE_ENV: ${{ inputs.NODE_ENV }}
          NEXT_PUBLIC_WWW_URL: ${{ secrets.NEXT_PUBLIC_WWW_URL }}
          NEXT_PUBLIC_BLOG_URL: ${{ secrets.NEXT_PUBLIC_BLOG_URL }}
          NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}
          S3_BUCKET_ACCESS_KEY_ID: ${{ secrets.S3_BUCKET_ACCESS_KEY_ID }}
          S3_BUCKET_SECRET_KEY: ${{ secrets.S3_BUCKET_SECRET_KEY }}
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
          KIT_API_KEY: ${{ secrets.KIT_API_KEY }}

      - uses: ./.github/actions/pnpm-install # docker already installs, ut we need this for the db migration
      - uses: ./.github/actions/db-migrate
        with:
          with_deploy: true
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - uses: ./.github/actions/koyeb-deploy
        with:
          NODE_ENV: ${{ inputs.NODE_ENV }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVICE_NAME: ${{ inputs.SERVICE_NAME}} # only blog for now

