name: CI / update changelog

on:
  workflow_call:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/pnpm-install

      - name: Generate Changeset via Codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm install -g @openai/codex
          codex -a auto-edit --quiet "create a .changeset/codex-update.md file describing recent changes"

      - name: Run Changeset version
        run: pnpm changeset version

      - name: Commit and push changelog + bumps
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: version bump via changesets [skip ci]" || echo "No changes to commit"
          git push origin main --follow-tags
