name: CD / Serverless Deployment

on:
  workflow_call:
    inputs:
      add_comment:
        description: "Add a comment notification to the PR"
        required: false
        type: string
        default: "false"
      deployment_environment:
        required: true
        type: string
        description: "Environment to deploy to (preview or production)"
      APP_NAME:
        required: true
        type: string
        description: "App name, either 'www' or 'blog' or whatever"

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment_environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}
      - uses: ./.github/actions/vercel-build
        with:
          APP_NAME: ${{ inputs.APP_NAME }}
          # tbh, im too lazy to go figure out VERCEL envs again, pain fr
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WWW_PROJECT_ID }}

      - uses: ./.github/actions/db-migrate
        with:
          with_deploy: "yes"

      - uses: ./.github/actions/vercel-deploy
        with:
          deployment_environment: ${{ inputs.deployment_environment }}
          APP_NAME: ${{ inputs.APP_NAME }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WWW_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
