name: CI / Database Fresh Migration

on:
  workflow_call:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/setup-env
        with:
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}

      - uses: ./.github/actions/setup-ephermal-db
      - name: Run fresh migrations on the ephermal database
        shell: bash
        run: |
          if [[ "$DATABASE_URL" != *"localhost"* ]] && [[ "$DATABASE_URL" != *"127.0.0.1"* ]]; then
            echo "❌ DATABASE_URL is not local! Aborting."
            exit 1
          fi

          echo "Running migration reset..."
          pnpm --filter @ashgw/db migrate:reset --force

          echo "Validating migrations..."
          pnpm --filter @ashgw/db migrate:status

          STATUS=$?
          echo "Cleaning up..."
          pnpm --filter @ashgw/db stop

          exit $STATUS
