name: CD / Docker App Deployment

on:
  workflow_call:
    inputs:
      NODE_ENV:
        required: true
        type: string
      SERVICE_NAME:
        required: true
        type: string
        description: blog or www or whatever, basically the app

jobs:
  deploy:
    environment: ${{ inputs.NODE_ENV }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          use_env_files: "yes"
          NODE_ENV: ${{ inputs.NODE_ENV }}
          NEXT_PUBLIC_WWW_URL: ${{ secrets.NEXT_PUBLIC_WWW_URL }}
          NEXT_PUBLIC_BLOG_URL: ${{ secrets.NEXT_PUBLIC_BLOG_URL }}
          NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}
          S3_BUCKET_ACCESS_KEY_ID: ${{ secrets.S3_BUCKET_ACCESS_KEY_ID }}
          S3_BUCKET_SECRET_KEY: ${{ secrets.S3_BUCKET_SECRET_KEY }}
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
          KIT_API_KEY: ${{ secrets.KIT_API_KEY }}
          IP_HASH_SALT: ${{ secrets.IP_HASH_SALT }}

      - uses: ./.github/actions/pnpm-install
      - uses: docker/setup-buildx-action@v3 # needed for db-migrate composite which spins a temp Postgres in Docker
      - uses: ./.github/actions/db-migrate
        with:
          with_deploy: true
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TEMPORARY_CONTAINER_DATABASE_URL: ${{ secrets.TEMPORARY_CONTAINER_DATABASE_URL }}

      - uses: ./.github/actions/koyeb-deploy
        with:
          NODE_ENV: ${{ inputs.NODE_ENV }}
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT_BLOG }}
          SERVICE_NAME: ${{ inputs.SERVICE_NAME}} # only blog for now

