name: CI

on:
  workflow_call:

jobs:
  unit-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 19, 20]

    services:
      db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: main
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 3s
          --health-timeout 2s
          --health-retries 10

      neon:
        image: ghcr.io/timowilhelm/local-neon-http-proxy:main
        ports:
          - 4444:4444
        env:
          PG_CONNECTION_STRING: postgres://postgres:postgres@db:5432/main
        options: >-
          --health-cmd "curl --fail http://localhost:4444/health || exit 1"
          --health-interval 3s
          --health-timeout 2s
          --health-retries 10

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client curl

      - name: Wait for proxy to be ready
        run: |
          for i in $(seq 1 30); do
            if curl --fail http://localhost:4444/health; then
              echo "Neon proxy is ready"
              break
            fi
            echo "Waiting for Neon proxy ($i)..."
            sleep 2
          done

      - uses: actions/checkout@v4

      - uses: ./.github/actions/pnpm-install
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ./.github/actions/setup-env
        with:
          NODE_ENV: "development"
          DATABASE_URL: postgres://postgres:postgres@localhost:4444/main?sslmode=disable
          NEXT_PUBLIC_WWW_URL: ${{ secrets.NEXT_PUBLIC_WWW_URL }}
          NEXT_PUBLIC_BLOG_URL: ${{ secrets.NEXT_PUBLIC_BLOG_URL }}
          NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}
          S3_BUCKET_ACCESS_KEY_ID: ${{ secrets.S3_BUCKET_ACCESS_KEY_ID }}
          S3_BUCKET_SECRET_KEY: ${{ secrets.S3_BUCKET_SECRET_KEY }}
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
          KIT_API_KEY: ${{ secrets.KIT_API_KEY }}

      - name: Setup Database Schema
        run: |
          export DATABASE_URL="postgres://postgres:postgres@localhost:4444/main?sslmode=disable"
          pnpm --filter @ashgw/db exec prisma migrate deploy

      - name: Run Unit + Integration Tests
        run: pnpm test:unit-integration

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: main
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 3s
          --health-timeout 2s
          --health-retries 10

      neon:
        image: ghcr.io/timowilhelm/local-neon-http-proxy:main
        ports:
          - 4444:4444
        env:
          PG_CONNECTION_STRING: postgres://postgres:postgres@db:5432/main
        options: >-
          --health-cmd "curl --fail http://localhost:4444/health || exit 1"
          --health-interval 3s
          --health-timeout 2s
          --health-retries 10

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client curl

      - name: Wait for proxy to be ready
        run: |
          for i in $(seq 1 30); do
            if curl --fail http://localhost:4444/health; then
              echo "Neon proxy is ready"
              break
            fi
            echo "Waiting for Neon proxy ($i)..."
            sleep 2
          done

      - uses: actions/checkout@v4

      - uses: ./.github/actions/pnpm-install
        with:
          node-version: 20 # or matrix like above

      - uses: ./.github/actions/setup-env
        with:
          NODE_ENV: "development"
          DATABASE_URL: postgres://postgres:postgres@localhost:4444/main?sslmode=disable

      - name: Setup Database Schema
        run: |
          export DATABASE_URL="postgres://postgres:postgres@localhost:4444/main?sslmode=disable"
          pnpm --filter @ashgw/db exec prisma migrate deploy

      - name: Run E2E Tests
        run: pnpm test:e2e
