name: CD / WWW production deployment

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      DEPLOY_ENV: production

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/vercel-build
        with:
          project_name: www
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}
          # deployment specific, not needed for build
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WWW_PROJECT_ID }}

      - uses: ./.github/actions/db-migrate
        with:
          with_deploy: "yes"
          environment: ${{ env.DEPLOY_ENV }}

      - uses: ./.github/actions/vercel-deploy
        with:
          environment: ${{ env.DEPLOY_ENV }}
          project_name: www
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
