name: CD / Blog to Koyeb

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/setup-env
        with:
          NODE_ENV: "production"
          NEXT_PUBLIC_WWW_URL: ${{ secrets.NEXT_PUBLIC_WWW_URL }}
          NEXT_PUBLIC_BLOG_URL: ${{ secrets.NEXT_PUBLIC_BLOG_URL }}
          NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}
          S3_BUCKET_ACCESS_KEY_ID: ${{ secrets.S3_BUCKET_ACCESS_KEY_ID }}
          S3_BUCKET_SECRET_KEY: ${{ secrets.S3_BUCKET_SECRET_KEY }}
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
          KIT_API_KEY: ${{ secrets.KIT_API_KEY }}

      - name: Set DATE_TAG
        run: echo "DATE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "ashgw" --password-stdin

      - name: Build and Push Docker Latest Image
        run: |
          docker build -t "ashgw/blog:latest" -f deployment/blog/Dockerfile .
          docker push "ashgw/blog:latest"

      - name: Push the preview image
        run: |
          docker tag ashgw/blog:latest ashgw/blog:preview
          docker push ashgw/blog:preview

      # - name: Push date-tagged image just incase I fuckup
      #   run: |
      #     docker tag ashgw/blog:latest ashgw/blog:${{ env.DATE_TAG }}
      #     docker push ashgw/blog:${{ env.DATE_TAG }}

      - name: Install Koyeb CLI and Redeploy
        run: |
          # Create the Koyeb config file directly, docs suck dawg
          cat > $HOME/.koyeb.yaml << EOF
          debug: false
          organization: ""
          token: ${{ secrets.KOYEB_TOKEN }}
          url: https://app.koyeb.com
          EOF

          # Install and configure CLI
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          export PATH=$HOME/.koyeb/bin:$PATH

          # Now directly use the CLI with the config file
          koyeb service redeploy blog/blog
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
