name: CD / Docker App Deployment

on:
  workflow_call:
    inputs:
      deployment_environment:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string
        description: blog or www or whatever, basically the app

jobs:
  deploy:
    environment: ${{ inputs.deployment_environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-env
        with:
          ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}

      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/db-migrate
        with:
          comment_on_pr: ${{ github.event_name == 'pull_request' && 'yes' || 'no' }}

      - uses: ./.github/actions/container-deploy
        with:
          environment: ${{ inputs.deployment_environment }}
          CONTAINER_DEPLOYMENT_SERVICE_TOKEN: ${{ secrets.CONTAINER_DEPLOYMENT_SERVICE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT_BLOG }}
          APP_NAME: ${{ inputs.APP_NAME}} # only blog for now
