name: CD / Blog production deployment

on:
  workflow_call:
    inputs:
      add_comment:
        description: "Add a comment notification to the PR"
        required: false
        type: string
        default: "false"

permissions:
  pull-requests: write # needed for adding comments
  contents: read # needed for reading secrets
  issues: write # needed for adding comments

jobs:
  deploy:
    uses: ./.github/workflows/on-workflow-call-container-deployment.yml
    with:
      NODE_ENV: "production"
    secrets: inherit
