name: CI / update changelog

on:
  workflow_call:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate short summary via LLM and append to global changelog
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip install llm
          COMMIT_MSG=$(git log -1 --pretty=%B)
          SHA=$(git rev-parse --short HEAD)
          OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          SAFE_MSG=$(printf '%s' "$COMMIT_MSG")
          SUMMARY=$(echo "$SAFE_MSG" | llm "Summarize this commit in one sentence (no prefix like 'this commit'; just directly say what it does):" | tr -d '\n')
          echo "[$SHA](https://github.com/$OWNER/$REPO/commit/$SHA) -> $SUMMARY" >> CHANGELOG.md

      - uses: ./.github/actions/pnpm-install

      - name: Run Changeset versioning
        run: pnpm changeset version

      - name: Create Pull Request for changelog update
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5
        with:
          commit-message: "chore: changelog + version bump [skip ci]"
          branch: chore/changelog-update
          title: "chore: update changelog and version bump"
          body: |
            This PR was auto-generated by CI to update the global changelog and apply version bumps via Changesets.
          labels: automated, changelog
          delete-branch: true
