name: CI

on:
  workflow_call:

jobs:
  unit-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 19, 20]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: main
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 2s
          --health-retries 10
      neon-proxy:
        image: ghcr.io/timowilhelm/local-neon-http-proxy:main
        env:
          PG_CONNECTION_STRING: postgresql://postgres:postgres@postgres:5432/main
          # Make services bind to all interfaces
          PROXY_LISTEN_ADDR: 0.0.0.0:4432
          HTTP_LISTEN_ADDR: 0.0.0.0:7001
          MGMT_LISTEN_ADDR: 0.0.0.0:7000
          WSS_LISTEN_ADDR: 0.0.0.0:4445
          # Disable features we don't need
          DISABLE_METRICS: "true"
          DISABLE_PARQUET_UPLOAD: "true"
          DISABLE_REGIONAL_REDIS: "true"
        ports:
          - 4444:4444
          - 4445:4445
          - 4432:4432
          - 7000:7000
          - 7001:7001
        options: >-
          --health-cmd "curl -f http://localhost:4444/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/setup-env
        with:
          NODE_ENV: "development"
          NEXT_PUBLIC_WWW_URL: ${{ secrets.NEXT_PUBLIC_WWW_URL }}
          NEXT_PUBLIC_BLOG_URL: ${{ secrets.NEXT_PUBLIC_BLOG_URL }}
          NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          DATABASE_URL: postgresql://postgres:postgres@localhost:4444/main
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}
          S3_BUCKET_ACCESS_KEY_ID: ${{ secrets.S3_BUCKET_ACCESS_KEY_ID }}
          S3_BUCKET_SECRET_KEY: ${{ secrets.S3_BUCKET_SECRET_KEY }}
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
          KIT_API_KEY: ${{ secrets.KIT_API_KEY }}

      - name: Setup Database Schema
        run: |
          export DATABASE_URL="postgresql://postgres:postgres@localhost:4444/main"
          pnpm --filter @ashgw/db exec prisma migrate deploy

      - name: Running code tests
        run: pnpm test:unit-integration

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: main
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 2s
          --health-retries 10
      neon-proxy:
        image: ghcr.io/timowilhelm/local-neon-http-proxy:main
        env:
          PG_CONNECTION_STRING: postgresql://postgres:postgres@postgres:5432/main
          # Make services bind to all interfaces
          PROXY_LISTEN_ADDR: 0.0.0.0:4432
          HTTP_LISTEN_ADDR: 0.0.0.0:7001
          MGMT_LISTEN_ADDR: 0.0.0.0:7000
          WSS_LISTEN_ADDR: 0.0.0.0:4445
          # Disable features we don't need
          DISABLE_METRICS: "true"
          DISABLE_PARQUET_UPLOAD: "true"
          DISABLE_REGIONAL_REDIS: "true"
        ports:
          - 4444:4444
          - 4445:4445
          - 4432:4432
          - 7000:7000
          - 7001:7001
        options: >-
          --health-cmd "curl -f http://localhost:4444/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/setup-env
        with:
          NODE_ENV: "development"
          NEXT_PUBLIC_WWW_URL: ${{ secrets.NEXT_PUBLIC_WWW_URL }}
          NEXT_PUBLIC_BLOG_URL: ${{ secrets.NEXT_PUBLIC_BLOG_URL }}
          NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_WWW_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_BLOG_GOOGLE_ANALYTICS_ID }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          DATABASE_URL: postgresql://postgres:postgres@localhost:4444/main
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}
          S3_BUCKET_ACCESS_KEY_ID: ${{ secrets.S3_BUCKET_ACCESS_KEY_ID }}
          S3_BUCKET_SECRET_KEY: ${{ secrets.S3_BUCKET_SECRET_KEY }}
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}

      - name: Setup Database Schema
        run: |
          export DATABASE_URL="postgresql://postgres:postgres@localhost:4444/main"
          pnpm --filter @ashgw/db exec prisma migrate deploy

      - name: Install dependencies
        run: npm install -g pnpm &&  pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install # issue not resolved with pnpm as of date 04.24
      - name: Run Playwright tests
        run: pnpm test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
