name: CD / Blog to Koyeb

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ashg/blog:latest -f deployment/blog/Dockerfile .
          docker push ashg/blog:latest

      - name: Install Koyeb CLI and Redeploy
        run: |
          curl -fsSL https://cli.koyeb.com/install.sh | sh
          koyeb auth login --token "${{ secrets.KOYEB_TOKEN }}"
          koyeb service redeploy docker-blog/latest
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
