name: PR / summarizer

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_SUBMODULE_SYNC_PAT }}

      - name: Summarize PR
        uses: ashgw/pr-summarizer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_PR_SUMMARIZER_KEY: ${{ secrets.OPENAI_PR_SUMMARIZER_KEY }}
          OPENAI_API_MODEL: "gpt-4o"
          exclude: "*.lock,dist/**,*.min.js,*.map"
          max_files: "130"
          owner: "author"
          override_summary: "true"
