name: CI / update changelog

on:
  workflow_call:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write # this is needed to allow pushing tags and committing

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Generate short summary via LLM and append to global changelog
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        run: |
          pip install llm 
          COMMIT_MSG=$(git log -1 --pretty=%B)
          SHA=$(git rev-parse --short HEAD)
          OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          SUMMARY=$(llm "Summarize this commit in one sentence (do not syat his commit does.. just directly say it): $COMMIT_MSG" | tr -d '\n')
          echo "[$SHA](https://github.com/$OWNER/$REPO/commit/$SHA) -> $SUMMARY" >> CHANGELOG.md

      - uses: ./.github/actions/pnpm-install
      - name: run Changeset versioning (if manually updated ofc with `pnpm changelog` => needs a human)
        run: pnpm changeset version

      - name: Commit and push changelog + bumps
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: version bump via changesets [skip ci]" || echo "No changes to commit"
          git push origin main --follow-tags
