name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Are you sure you want to deploy to production?'
        required: true
        type: boolean
        default: false

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_deploy == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-pnpm-setup
      - uses: ./.github/actions/setup-env
        with:
          env_vars: ${{ secrets.ENV_VARS }}
          ga_id: ${{ secrets.GA_ID }}
      - uses: ./.github/actions/pnpm-install

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel deploy --prod --token=$VERCEL_TOKEN --yes
