name: Production Deployment

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-production:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-pnpm-setup
      - uses: ./.github/actions/setup-env
        with:
          env_vars: ${{ secrets.ENV_VARS }}
          ga_id: ${{ secrets.GA_ID }}
      - uses: ./.github/actions/pnpm-install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Link to Vercel Project
        run: vercel link --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel Production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel deploy --prod --token=$VERCEL_TOKEN --yes
