name: test

on:
  push:
    branches:
      - main
      - prod-preview
  pull_request:
    branches:
      - main
      - prod-preview
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18, 19, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Set up .env
        run: echo '${{ secrets.ENV_VARS }}' >> .env.local
      - name: Install dependencies w/ setup
        run: pnpm i
      - name: Running code tests
        run: npx jest --testPathPattern=code

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Set up .env
        run: echo '${{ secrets.ENV_VARS }}' >> .env.local
      - name: Install dependencies w/ setup
        run: pnpm i
      - name: lint
        run: pnpm lint
