name: CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  unit-integration:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18, 19, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-pnpm-setup
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/setup-env
        with:
          env_vars: ${{ secrets.ENV_VARS }}
          ga_id: ${{ secrets.GA_ID }}
      - uses: ./.github/actions/pnpm-install

      - name: Running code tests
        run: npx jest
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-pnpm-setup
      - uses: ./.github/actions/setup-env
        with:
          env_vars: ${{ secrets.ENV_VARS }}
          ga_id: ${{ secrets.GA_ID }}
      - name: Install dependencies
        run: npm install -g pnpm &&  pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install # issue not resolved with pnpm
      - name: Run Playwright tests
        run: cd test/e2e &&  npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
