name: CI

on:
  workflow_dispatch:
  workflow_call:

jobs:
  unit-integration:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18, 19, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-install
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/setup-env
        with:
          ENV_VARS: ${{ secrets.ENV_VARS }}
          GA_ID: ${{ secrets.GA_ID }}
      - name: Running code tests
        run: pnpm test:unit-integration

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm-install
      - uses: ./.github/actions/setup-env
        with:
          ENV_VARS: ${{ secrets.ENV_VARS }}
          GA_ID: ${{ secrets.GA_ID }}
      - name: Install dependencies
        run: npm install -g pnpm &&  pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install # issue not resolved with pnpm as of date 04.24
      - name: Run Playwright tests
        run: pnpm test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
