name: CI / DB Migrate

description: Run database migrations

inputs:
  with_deploy:
    required: true
    description: "Whether to run the migration deployment step ('yes' or 'no')"

runs:
  using: "composite"
  steps:
    - name: Mask database url and set the actual database url
      shell: bash
      run: |
        set -euo pipefail
        if [[ -z "${DATABASE_URL:-}" ]]; then
          echo "DATABASE_URL is not set"; exit 1
        fi
        echo "::add-mask::$DATABASE_URL"
        echo ACTUAL_DATABASE_URL=$DATABASE_URL >> $GITHUB_ENV

    - name: Start an ephemeral database
      uses: ./.github/actions/setup-ephermal-database
    - name: Test migrations in an ephemeral Docker container
      shell: bash
      run: |
        echo "Running migration reset..."
        pnpm --filter @ashgw/db migrate:reset --force

        echo "Validating migrations..."
        pnpm --filter @ashgw/db migrate:status

        STATUS=$?
        echo "Cleaning up..."
        pnpm --filter @ashgw/db stop

        exit $STATUS

    - name: Set the database url back to the original
      shell: bash
      run: |
        echo "DATABASE_URL=$ACTUAL_DATABASE_URL" >> $GITHUB_ENV

    - name: Check for schema drift on the $CURRENT_ENV database
      shell: bash
      run: |
        pnpm --filter @ashgw/db exec prisma migrate diff \
        --from-url="$DATABASE_URL" \
        --to-schema-datamodel=./prisma/schema.prisma \
        --script > migration.sql 2>&1

        chmod +x .github/scripts/check-migration-safety.sh
        .github/scripts/check-migration-safety.sh migration.sql

    - name: Deploy migrations on the $CURRENT_ENV database
      if: inputs.with_deploy == 'yes'
      shell: bash
      run: |
        pnpm --filter @ashgw/db exec prisma migrate deploy 2>&1 | grep -v "Datasource" | grep -v "database" | grep -v "schema" | grep -v "at"

    - name: Validate migrations on the $CURRENT_ENV database
      if: inputs.with_deploy == 'yes'
      shell: bash
      run: |
        pnpm --filter @ashgw/db exec prisma migrate status 2>&1 | grep -v "Datasource" | grep -v "database" | grep -v "schema" | grep -v "at"

    - name: Comment on PR
      if: github.event_name == 'pull_request' && inputs.with_deploy == 'yes'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}

      run: |
        pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        repo="${{ github.repository }}"

        comment_body="Database migrations were successfully deployed to the $CURRENT_ENV branch of the database."

        curl -s -X POST \
          -H "Authorization: token $GH_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"${comment_body}\"}" \
          "https://api.github.com/repos/${repo}/issues/${pr_number}/comments"
