name: CI / DB Migrate

description: Run database migrations (against the real DB)

inputs:
  comment_on_pr:
    required: true
    description: "Whether to comment on the PR ('yes' or 'no') after running the migration"

runs:
  using: "composite"
  steps:
    - name: Deploy pending migrations on the $NEXT_PUBLIC_CURRENT_ENV database
      shell: bash
      run: |
        pnpm --filter @ashgw/db exec prisma migrate deploy 2>&1 | grep -v "Datasource" | grep -v "database" | grep -v "schema" | grep -v "at"

    - name: Comment on PR
      if: github.event_name == 'pull_request' && inputs.comment_on_pr == 'yes'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}

      run: |
        pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        repo="${{ github.repository }}"

        comment_body="Database migrations were successfully deployed to the $NEXT_PUBLIC_CURRENT_ENV branch of the database."

        curl -s -X POST \
          -H "Authorization: token $GH_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"${comment_body}\"}" \
          "https://api.github.com/repos/${repo}/issues/${pr_number}/comments"
