name: Ephemeral Postgres
description: Start a simple temporary Postgres in Docker

runs:
  using: "composite"
  steps:
    - name: Set up Docker for the temporary database container
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
    - name: Run Postgres
      id: pg
      shell: bash
      run: |
        pnpm --filter @ashgw/db start
        echo "Waiting for DB to be ready..."
        for i in {1..30}; do
          pg_isready -h localhost -p 5432 -U postgres && break
          sleep 2
        done
        # I already set the TEMPORARY_CONTAINER_DATABASE_URL env var in the env step.
